apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  namespace: booking-tickets
data:
  APP_TITLE: "Auth Service"
  DEBUG: "false"
  SQL_ECHO: "false"
  ENVIRONMENT: "production"
  POSTGRES_SERVER: "postgres-auth"
  POSTGRES_PORT: "5432"
  ALGORITHM: "RS256"
  JWT_ISSUER: "booking-auth-service"
