apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-worker
  namespace: booking-tickets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-worker
  template:
    metadata:
      labels:
        app: notification-worker
    spec:
      automountServiceAccountToken: false
      containers:
        - name: notification-worker
          image: docker.io/library/booking_tickets-notification_worker:latest
          imagePullPolicy: Never
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          command:
            - celery
            - -A
            - src.worker
            - worker
            - --loglevel=info
            - --concurrency=2
          env:
            - name: RABBITMQ_HOST
              value: "rabbitmq"
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: booking-tickets-secrets
                  key: rabbitmq-user
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: booking-tickets-secrets
                  key: rabbitmq-password
            - name: RABBITMQ_VHOST
              valueFrom:
                secretKeyRef:
                  name: booking-tickets-secrets
                  key: rabbitmq-vhost
            - name: SMTP_HOST
              value: "smtp.gmail.com"
            - name: SMTP_PORT
              value: "587"
            - name: SMTP_USER
              valueFrom:
                secretKeyRef:
                  name: booking-tickets-secrets
                  key: smtp-user
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: booking-tickets-secrets
                  key: smtp-password
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
