apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-http-to-app-services
  namespace: booking-tickets
spec:
  podSelector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - auth-service
          - booking-service
          - event-service
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
      ports:
        - protocol: TCP
          port: 8000
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: booking-tickets
      ports:
        - protocol: TCP
          port: 8000
