apiVersion: v1
kind: Secret
metadata:
  name: booking-tickets-secrets
  namespace: booking-tickets
type: Opaque
stringData:
  event-postgres-user: "event_user"
  event-postgres-password: "replace-me"
  event-postgres-db: "booking_event_db"

  auth-postgres-user: "auth_user"
  auth-postgres-password: "replace-me"
  auth-postgres-db: "auth_db"

  booking-postgres-user: "booking_user"
  booking-postgres-password: "replace-me"
  booking-postgres-db: "booking_db"

  rabbitmq-user: "booking_rabbit"
  rabbitmq-password: "replace-me"
  rabbitmq-vhost: "booking"

  smtp-user: "mailer@example.com"
  smtp-password: "replace-me"

  jwt-private-key: |
    -----BEGIN PRIVATE KEY-----
    replace-me
    -----END PRIVATE KEY-----
  jwt-public-key: |
    -----BEGIN PUBLIC KEY-----
    replace-me
    -----END PUBLIC KEY-----
