"""create users table

Revision ID: 3cd211bc997d
Revises:
Create Date: 2026-03-23 19:35:44.735533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cd211bc997d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Применяет миграцию."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('email', sa.String(length=255), nullable=False),
                    sa.Column('hashed_password', sa.String(
                        length=60), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('role', sa.String(length=50), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    schema='auth'
                    )
    op.create_index(op.f('ix_auth_users_email'), 'users',
                    ['email'], unique=True, schema='auth')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Откатывает миграцию."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_users_email'),
                  table_name='users', schema='auth')
    op.drop_table('users', schema='auth')
    # ### end Alembic commands ###
